development: &defaults

  # These are the settings for repository :default
  adapter:  mysql
  database: todos_development
  username: root
  password: 
  host:     localhost

test:
  <<:       *defaults
  database: todos_test

production:
  <<:       *defaults
  database: todos_production

